-- MySQL Script generated by MySQL Workbench
-- Sun Jun 29 09:01:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema soal1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soal1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soal1` DEFAULT CHARACTER SET utf8mb4 ;
USE `soal1` ;

-- -----------------------------------------------------
-- Table `acudiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acudiente` ;

CREATE TABLE IF NOT EXISTS `acudiente` (
  `id_acudiente` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_documento` VARCHAR(20) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  `id_relacion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_acudiente`),
  INDEX `numero_documento` (`numero_documento` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_relacion` (`id_relacion` ASC) VISIBLE,
  CONSTRAINT `acudiente_ibfk_1`
    FOREIGN KEY (`numero_documento`)
    REFERENCES `persona` (`numero_documento`),
  CONSTRAINT `acudiente_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuario` (`id_usuario`),
  CONSTRAINT `acudiente_ibfk_3`
    FOREIGN KEY (`id_relacion`)
    REFERENCES `relacion_acudiente` (`id_relacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asistencia` ;

CREATE TABLE IF NOT EXISTS `asistencia` (
  `id_asistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NOT NULL,
  `id_funcionario` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `id_estado_asistencia` INT(11) NOT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_asistencia`),
  INDEX `id_estudiante` (`id_estudiante` ASC) VISIBLE,
  INDEX `id_funcionario` (`id_funcionario` ASC) VISIBLE,
  INDEX `id_estado_asistencia` (`id_estado_asistencia` ASC) VISIBLE,
  CONSTRAINT `asistencia_ibfk_1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `estudiante` (`id_estudiante`),
  CONSTRAINT `asistencia_ibfk_2`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `funcionario` (`id_funcionario`),
  CONSTRAINT `asistencia_ibfk_3`
    FOREIGN KEY (`id_estado_asistencia`)
    REFERENCES `estado_asistencia` (`id_estado_asistencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `auditoria_observacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditoria_observacion` ;

CREATE TABLE IF NOT EXISTS `auditoria_observacion` (
  `id_auditoria` INT(11) NOT NULL AUTO_INCREMENT,
  `id_observacion` INT(11) NULL DEFAULT NULL,
  `accion` VARCHAR(10) NULL DEFAULT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_auditoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `canal_notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canal_notificacion` ;

CREATE TABLE IF NOT EXISTS `canal_notificacion` (
  `id_canal` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_canal`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `categoria_observacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria_observacion` ;

CREATE TABLE IF NOT EXISTS `categoria_observacion` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cita` ;

CREATE TABLE IF NOT EXISTS `cita` (
  `id_cita` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NOT NULL,
  `id_acudiente` INT(11) NOT NULL,
  `id_funcionario` INT(11) NOT NULL,
  `fecha_cita` DATETIME NOT NULL,
  `motivo` TEXT NOT NULL,
  `estado` VARCHAR(20) NULL DEFAULT 'Pendiente',
  PRIMARY KEY (`id_cita`),
  INDEX `cita_ibfk_1` (`id_estudiante` ASC) VISIBLE,
  INDEX `cita_ibfk_2` (`id_acudiente` ASC) VISIBLE,
  INDEX `cita_ibfk_3` (`id_funcionario` ASC) VISIBLE,
  INDEX `idx_fecha_cita` (`fecha_cita` ASC) VISIBLE,
  CONSTRAINT `cita_ibfk_1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `estudiante` (`id_estudiante`)
    ON DELETE CASCADE,
  CONSTRAINT `cita_ibfk_2`
    FOREIGN KEY (`id_acudiente`)
    REFERENCES `acudiente` (`id_acudiente`)
    ON DELETE CASCADE,
  CONSTRAINT `cita_ibfk_3`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `funcionario` (`id_funcionario`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `eps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eps` ;

CREATE TABLE IF NOT EXISTS `eps` (
  `id_eps` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_eps`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `estado_academico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado_academico` ;

CREATE TABLE IF NOT EXISTS `estado_academico` (
  `id_estado_academico` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado_academico`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `estado_asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado_asistencia` ;

CREATE TABLE IF NOT EXISTS `estado_asistencia` (
  `id_estado_asistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_estado_asistencia`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `estado_notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado_notificacion` ;

CREATE TABLE IF NOT EXISTS `estado_notificacion` (
  `id_estado_notificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_estado_notificacion`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `estado_pqr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado_pqr` ;

CREATE TABLE IF NOT EXISTS `estado_pqr` (
  `id_estado_pqr` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado_pqr`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `estado_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado_usuario` ;

CREATE TABLE IF NOT EXISTS `estado_usuario` (
  `id_estado_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_estado_usuario`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiante` ;

CREATE TABLE IF NOT EXISTS `estudiante` (
  `id_estudiante` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_documento` VARCHAR(20) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  `id_eps` INT(11) NULL DEFAULT NULL,
  `id_estado_academico` INT(11) NULL DEFAULT NULL,
  `id_acudiente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estudiante`),
  INDEX `numero_documento` (`numero_documento` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_estado_academico` (`id_estado_academico` ASC) VISIBLE,
  INDEX `id_acudiente` (`id_acudiente` ASC) VISIBLE,
  INDEX `idx_estudiante_eps_estado` (`id_eps` ASC, `id_estado_academico` ASC) VISIBLE,
  CONSTRAINT `estudiante_ibfk_1`
    FOREIGN KEY (`numero_documento`)
    REFERENCES `persona` (`numero_documento`),
  CONSTRAINT `estudiante_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuario` (`id_usuario`),
  CONSTRAINT `estudiante_ibfk_3`
    FOREIGN KEY (`id_eps`)
    REFERENCES `eps` (`id_eps`),
  CONSTRAINT `estudiante_ibfk_4`
    FOREIGN KEY (`id_estado_academico`)
    REFERENCES `estado_academico` (`id_estado_academico`),
  CONSTRAINT `estudiante_ibfk_5`
    FOREIGN KEY (`id_acudiente`)
    REFERENCES `acudiente` (`id_acudiente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `estudiante_grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiante_grado` ;

CREATE TABLE IF NOT EXISTS `estudiante_grado` (
  `id_estudiante_grado` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NULL DEFAULT NULL,
  `id_grado` INT(11) NULL DEFAULT NULL,
  `anio_academico` YEAR(4) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id_estudiante_grado`),
  INDEX `estudiante_grado_ibfk_1` (`id_estudiante` ASC) VISIBLE,
  INDEX `estudiante_grado_ibfk_2` (`id_grado` ASC) VISIBLE,
  CONSTRAINT `estudiante_grado_ibfk_1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `estudiante` (`id_estudiante`)
    ON DELETE CASCADE,
  CONSTRAINT `estudiante_grado_ibfk_2`
    FOREIGN KEY (`id_grado`)
    REFERENCES `grado` (`id_grado`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionario` ;

CREATE TABLE IF NOT EXISTS `funcionario` (
  `id_funcionario` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_documento` VARCHAR(20) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  `cargo` VARCHAR(50) NULL DEFAULT NULL,
  `id_escolaridad` INT(11) NULL DEFAULT NULL,
  `arl` VARCHAR(50) NULL DEFAULT NULL,
  `foto` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `numero_documento` (`numero_documento` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_escolaridad` (`id_escolaridad` ASC) VISIBLE,
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`numero_documento`)
    REFERENCES `persona` (`numero_documento`),
  CONSTRAINT `funcionario_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuario` (`id_usuario`),
  CONSTRAINT `funcionario_ibfk_3`
    FOREIGN KEY (`id_escolaridad`)
    REFERENCES `nivel_escolaridad` (`id_escolaridad`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `funcionario_grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionario_grado` ;

CREATE TABLE IF NOT EXISTS `funcionario_grado` (
  `id_funcionario_grado` INT(11) NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT(11) NULL DEFAULT NULL,
  `id_grado` INT(11) NULL DEFAULT NULL,
  `rol` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcionario_grado`),
  INDEX `id_grado` (`id_grado` ASC) VISIBLE,
  INDEX `funcionario_grado_ibfk_1` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `funcionario_grado_ibfk_1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `funcionario` (`id_funcionario`)
    ON DELETE CASCADE,
  CONSTRAINT `funcionario_grado_ibfk_2`
    FOREIGN KEY (`id_grado`)
    REFERENCES `grado` (`id_grado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grado` ;

CREATE TABLE IF NOT EXISTS `grado` (
  `id_grado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_grado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_grado`),
  UNIQUE INDEX `nombre_grado` (`nombre_grado` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gravedad_observacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gravedad_observacion` ;

CREATE TABLE IF NOT EXISTS `gravedad_observacion` (
  `id_gravedad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_gravedad`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `justificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `justificacion` ;

CREATE TABLE IF NOT EXISTS `justificacion` (
  `id_justificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `motivo` TEXT NOT NULL,
  `archivo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_justificacion`),
  INDEX `justificacion_ibfk_1` (`id_estudiante` ASC) VISIBLE,
  INDEX `idx_justificacion_fecha` (`fecha` ASC) VISIBLE,
  CONSTRAINT `justificacion_ibfk_1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `estudiante` (`id_estudiante`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `nivel_escolaridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nivel_escolaridad` ;

CREATE TABLE IF NOT EXISTS `nivel_escolaridad` (
  `id_escolaridad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_escolaridad`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notificacion` ;

CREATE TABLE IF NOT EXISTS `notificacion` (
  `id_notificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_acudiente` INT(11) NOT NULL,
  `mensaje` TEXT NOT NULL,
  `fecha_envio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_canal` INT(11) NOT NULL,
  `id_estado_notificacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_notificacion`),
  INDEX `id_canal` (`id_canal` ASC) VISIBLE,
  INDEX `notificacion_ibfk_1` (`id_acudiente` ASC) VISIBLE,
  INDEX `idx_notificacion_estado_fecha` (`id_estado_notificacion` ASC, `fecha_envio` ASC) VISIBLE,
  CONSTRAINT `notificacion_ibfk_1`
    FOREIGN KEY (`id_acudiente`)
    REFERENCES `acudiente` (`id_acudiente`)
    ON DELETE CASCADE,
  CONSTRAINT `notificacion_ibfk_2`
    FOREIGN KEY (`id_canal`)
    REFERENCES `canal_notificacion` (`id_canal`),
  CONSTRAINT `notificacion_ibfk_3`
    FOREIGN KEY (`id_estado_notificacion`)
    REFERENCES `estado_notificacion` (`id_estado_notificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `observacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `observacion` ;

CREATE TABLE IF NOT EXISTS `observacion` (
  `id_observacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT(11) NOT NULL,
  `id_funcionario` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` TEXT NOT NULL,
  `id_gravedad` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_observacion`),
  INDEX `id_gravedad` (`id_gravedad` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `idx_observacion_funcionario_fecha` (`id_funcionario` ASC, `fecha` ASC) VISIBLE,
  INDEX `idx_observacion_estudiante_fecha` (`id_estudiante` ASC, `fecha` ASC) VISIBLE,
  CONSTRAINT `observacion_ibfk_1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `estudiante` (`id_estudiante`)
    ON DELETE CASCADE,
  CONSTRAINT `observacion_ibfk_2`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `funcionario` (`id_funcionario`)
    ON DELETE CASCADE,
  CONSTRAINT `observacion_ibfk_3`
    FOREIGN KEY (`id_gravedad`)
    REFERENCES `gravedad_observacion` (`id_gravedad`),
  CONSTRAINT `observacion_ibfk_4`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `categoria_observacion` (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persona` ;

CREATE TABLE IF NOT EXISTS `persona` (
  `numero_documento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `id_sexo` INT(11) NOT NULL,
  `id_tipo_documento` INT(11) NOT NULL,
  PRIMARY KEY (`numero_documento`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `id_sexo` (`id_sexo` ASC) VISIBLE,
  INDEX `id_tipo_documento` (`id_tipo_documento` ASC) VISIBLE,
  CONSTRAINT `persona_ibfk_1`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `sexo` (`id_sexo`),
  CONSTRAINT `persona_ibfk_2`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `tipo_documento` (`id_tipo_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pqr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pqr` ;

CREATE TABLE IF NOT EXISTS `pqr` (
  `id_pqr` INT(11) NOT NULL AUTO_INCREMENT,
  `id_acudiente` INT(11) NOT NULL,
  `id_estudiante` INT(11) NULL DEFAULT NULL,
  `id_tipo_pqr` INT(11) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `id_estado_pqr` INT(11) NOT NULL,
  PRIMARY KEY (`id_pqr`),
  INDEX `id_tipo_pqr` (`id_tipo_pqr` ASC) VISIBLE,
  INDEX `pqr_ibfk_1` (`id_acudiente` ASC) VISIBLE,
  INDEX `pqr_ibfk_2` (`id_estudiante` ASC) VISIBLE,
  INDEX `idx_estado_pqr` (`id_estado_pqr` ASC) VISIBLE,
  CONSTRAINT `pqr_ibfk_1`
    FOREIGN KEY (`id_acudiente`)
    REFERENCES `acudiente` (`id_acudiente`)
    ON DELETE CASCADE,
  CONSTRAINT `pqr_ibfk_2`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `estudiante` (`id_estudiante`)
    ON DELETE CASCADE,
  CONSTRAINT `pqr_ibfk_3`
    FOREIGN KEY (`id_tipo_pqr`)
    REFERENCES `tipo_pqr` (`id_tipo_pqr`),
  CONSTRAINT `pqr_ibfk_4`
    FOREIGN KEY (`id_estado_pqr`)
    REFERENCES `estado_pqr` (`id_estado_pqr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `relacion_acudiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relacion_acudiente` ;

CREATE TABLE IF NOT EXISTS `relacion_acudiente` (
  `id_relacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_relacion`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sexo` ;

CREATE TABLE IF NOT EXISTS `sexo` (
  `id_sexo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sexo`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_documento` ;

CREATE TABLE IF NOT EXISTS `tipo_documento` (
  `id_tipo_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_documento`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tipo_pqr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_pqr` ;

CREATE TABLE IF NOT EXISTS `tipo_pqr` (
  `id_tipo_pqr` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_pqr`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `tipo_usuario` (
  `id_tipo_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `numero_documento` VARCHAR(20) NULL DEFAULT NULL,
  `id_tipo_usuario` INT(11) NULL DEFAULT NULL,
  `id_estado_usuario` INT(11) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `numero_documento` (`numero_documento` ASC) VISIBLE,
  INDEX `id_tipo_usuario` (`id_tipo_usuario` ASC) VISIBLE,
  INDEX `id_estado_usuario` (`id_estado_usuario` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`numero_documento`)
    REFERENCES `persona` (`numero_documento`),
  CONSTRAINT `usuario_ibfk_2`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `tipo_usuario` (`id_tipo_usuario`),
  CONSTRAINT `usuario_ibfk_3`
    FOREIGN KEY (`id_estado_usuario`)
    REFERENCES `estado_usuario` (`id_estado_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;

USE `soal1` ;

-- -----------------------------------------------------
-- procedure inactivar_usuario
-- -----------------------------------------------------

USE `soal1`;
DROP procedure IF EXISTS `inactivar_usuario`;

DELIMITER $$
USE `soal1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `inactivar_usuario`(IN p_id_usuario INT)
BEGIN
  UPDATE usuario
  SET id_estado_usuario = 2
  WHERE id_usuario = p_id_usuario;
END$$

DELIMITER ;
USE `soal1`;

DELIMITER $$

USE `soal1`$$
DROP TRIGGER IF EXISTS `trg_insert_observacion` $$
USE `soal1`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `soal1`.`trg_insert_observacion`
AFTER INSERT ON `soal1`.`observacion`
FOR EACH ROW
BEGIN
  INSERT INTO auditoria_observacion (id_observacion, accion)
  VALUES (NEW.id_observacion, 'INSERT');
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
